import jsPDF from "jspdf";
import type { TenancyCardData } from "@/components/TenancyCard";

export const generateTenancyCardPdf = (data: TenancyCardData): jsPDF => {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: [140, 90] });

  // Header
  doc.setFillColor(20, 60, 100);
  doc.rect(0, 0, 140, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("RENT CONTROL — TENANCY CARD", 70, 7, { align: "center" });
  doc.setFontSize(7);
  doc.text(`ID: ${data.registrationCode}`, 70, 13, { align: "center" });

  // Body
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");

  const rows: [string, string][] = [
    ["Property ID", data.propertyId.slice(0, 12) + "..."],
    ["Digital Address", data.digitalAddress || "—"],
    ["Landlord", data.landlordName],
    ["Tenant", data.tenantName],
    ["Monthly Rent", `GH₵ ${data.monthlyRent.toLocaleString()}`],
    ["Max Lawful Advance", `GH₵ ${data.maxLawfulAdvance.toLocaleString()}`],
    ["Advance Paid", `${data.advancePaid} month(s)`],
    ["Start Date", data.startDate],
    ["Expiry Date", data.expiryDate],
  ];

  // Add rent card serials with role labels
  if (data.rentCardSerial) {
    const label = data.rentCardRole === "landlord_copy" ? "Card (Landlord)" : data.rentCardRole === "tenant_copy" ? "Card (Tenant)" : "Rent Card";
    rows.push([label, data.rentCardSerial]);
  }
  if (data.rentCardSerial2) {
    const label = data.rentCardRole2 === "tenant_copy" ? "Card (Tenant)" : data.rentCardRole2 === "landlord_copy" ? "Card (Landlord)" : "Rent Card 2";
    rows.push([label, data.rentCardSerial2]);
  }

  rows.push(
    ["Compliance", data.complianceStatus],
    ["Status", data.status],
  );

  let y = 21;
  const col1 = 5;
  const col2 = 45;
  const col3 = 75;
  const col4 = 110;

  for (let i = 0; i < rows.length; i += 2) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(rows[i][0], col1, y);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.text(rows[i][1], col2, y);

    if (rows[i + 1]) {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(rows[i + 1][0], col3, y);
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", "bold");
      doc.text(rows[i + 1][1], col4, y);
    }
    y += 6;
  }

  // Footer
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 78, 140, 12, "F");
  doc.setFontSize(6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Verify: rentghanapilot.lovable.app/verify-tenancy/" + (data as any).tenancyId, 5, 84);
  doc.text("Generated by RentControlGhana", 135, 84, { align: "right" });

  return doc;
};
