import { useState } from "react";
import { FileText, Settings, Info } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const RegulatorAgreementTemplates = () => {
  const [templateConfig, setTemplateConfig] = useState({
    maxAdvanceMonths: 6,
    minLeaseDuration: 1,
    maxLeaseDuration: 24,
    taxRate: 8,
    registrationDeadlineDays: 14,
    terms: [
      "The Tenant shall pay rent monthly, including the statutory 8% government tax through the Rent Control app.",
      "Advance rent shall not exceed 6 months as mandated by Act 220.",
      "This agreement must be registered within 14 days of signing.",
      "The Landlord shall maintain the property in habitable condition.",
      "Neither party may unilaterally vary the terms without due process.",
      "The tenancy is only valid for months where the 8% tax has been paid.",
    ],
  });

  const [editingTermIndex, setEditingTermIndex] = useState<number | null>(null);
  const [newTerm, setNewTerm] = useState("");

  const updateField = (field: string, value: any) => {
    setTemplateConfig(prev => ({ ...prev, [field]: value }));
  };

  const updateTerm = (index: number, value: string) => {
    const updated = [...templateConfig.terms];
    updated[index] = value;
    setTemplateConfig(prev => ({ ...prev, terms: updated }));
  };

  const removeTerm = (index: number) => {
    setTemplateConfig(prev => ({ ...prev, terms: prev.terms.filter((_, i) => i !== index) }));
  };

  const addTerm = () => {
    if (!newTerm.trim()) return;
    setTemplateConfig(prev => ({ ...prev, terms: [...prev.terms, newTerm.trim()] }));
    setNewTerm("");
  };

  const handleSave = () => {
    // In production, this would save to database
    toast.success("Agreement template configuration saved");
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-foreground flex items-center gap-2">
          <Settings className="h-7 w-7 text-primary" /> Agreement Template Configuration
        </h1>
        <p className="text-muted-foreground mt-1">Configure the standardized tenancy agreement fields and allowed values</p>
      </div>

      <div className="bg-card rounded-xl border border-border shadow-card p-6 space-y-6">
        <div className="flex items-center gap-2 text-sm text-info bg-info/10 rounded-lg p-3">
          <Info className="h-4 w-4 shrink-0" />
          <span>These settings define the rules enforced across all tenancy agreements generated by the system, in compliance with the Rent Act 220.</span>
        </div>

        <div className="grid sm:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="maxAdvance">Maximum Advance Rent (months)</Label>
            <Input
              id="maxAdvance"
              type="number"
              min={1}
              max={12}
              value={templateConfig.maxAdvanceMonths}
              onChange={e => updateField("maxAdvanceMonths", parseInt(e.target.value) || 6)}
            />
            <p className="text-xs text-muted-foreground">Act 220 mandates a maximum of 6 months advance rent</p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="taxRate">Government Tax Rate (%)</Label>
            <Input
              id="taxRate"
              type="number"
              min={0}
              max={50}
              value={templateConfig.taxRate}
              onChange={e => updateField("taxRate", parseFloat(e.target.value) || 8)}
            />
            <p className="text-xs text-muted-foreground">Statutory tax collected on monthly rent</p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="minLease">Minimum Lease Duration (months)</Label>
            <Input
              id="minLease"
              type="number"
              min={1}
              max={60}
              value={templateConfig.minLeaseDuration}
              onChange={e => updateField("minLeaseDuration", parseInt(e.target.value) || 1)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="maxLease">Maximum Lease Duration (months)</Label>
            <Input
              id="maxLease"
              type="number"
              min={1}
              max={120}
              value={templateConfig.maxLeaseDuration}
              onChange={e => updateField("maxLeaseDuration", parseInt(e.target.value) || 24)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="regDeadline">Registration Deadline (days after signing)</Label>
            <Input
              id="regDeadline"
              type="number"
              min={1}
              max={90}
              value={templateConfig.registrationDeadlineDays}
              onChange={e => updateField("registrationDeadlineDays", parseInt(e.target.value) || 14)}
            />
            <p className="text-xs text-muted-foreground">Number of days allowed to register a new agreement</p>
          </div>
        </div>
      </div>

      {/* Terms & Conditions */}
      <div className="bg-card rounded-xl border border-border shadow-card p-6 space-y-4">
        <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" /> Standard Terms & Conditions
        </h2>
        <p className="text-sm text-muted-foreground">These terms appear in every generated tenancy agreement PDF.</p>

        <div className="space-y-3">
          {templateConfig.terms.map((term, index) => (
            <div key={index} className="flex gap-2 items-start">
              <span className="text-xs font-mono text-muted-foreground pt-2.5 shrink-0 w-6">{index + 1}.</span>
              {editingTermIndex === index ? (
                <div className="flex-1 space-y-2">
                  <Textarea
                    value={term}
                    onChange={e => updateTerm(index, e.target.value)}
                    className="min-h-[60px]"
                  />
                  <div className="flex gap-2">
                    <Button size="sm" onClick={() => setEditingTermIndex(null)}>Save</Button>
                    <Button size="sm" variant="ghost" onClick={() => setEditingTermIndex(null)}>Cancel</Button>
                  </div>
                </div>
              ) : (
                <div className="flex-1 flex items-start gap-2">
                  <p className="text-sm text-foreground flex-1 pt-1">{term}</p>
                  <div className="flex gap-1 shrink-0">
                    <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setEditingTermIndex(index)}>Edit</Button>
                    <Button size="sm" variant="ghost" className="h-7 text-xs text-destructive hover:text-destructive" onClick={() => removeTerm(index)}>Remove</Button>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="flex gap-2 pt-2 border-t border-border">
          <Input
            placeholder="Add a new term or condition..."
            value={newTerm}
            onChange={e => setNewTerm(e.target.value)}
            onKeyDown={e => e.key === "Enter" && addTerm()}
            className="flex-1"
          />
          <Button onClick={addTerm} disabled={!newTerm.trim()}>Add Term</Button>
        </div>
      </div>

      {/* Agreement template preview info */}
      <div className="bg-card rounded-xl border border-border shadow-card p-6 space-y-3">
        <h2 className="text-lg font-semibold text-foreground">Template Fields</h2>
        <p className="text-sm text-muted-foreground">The following fields are automatically populated in each tenancy agreement:</p>
        <div className="grid sm:grid-cols-2 gap-2 text-sm">
          {[
            "Registration Code", "Date of Agreement", "Landlord Name", "Tenant Name",
            "Tenant ID", "Property Name", "Property Address", "Unit Name & Type",
            "Region", "Monthly Rent", "Advance Period", "Total Advance Amount",
            "Government Tax (8%)", "Amount to Landlord (92%)", "Tenancy Start Date",
            "Tenancy End Date", "Landlord Signature", "Tenant Signature",
          ].map(field => (
            <div key={field} className="flex items-center gap-2 py-1.5 px-3 rounded-lg bg-muted/50">
              <div className="h-1.5 w-1.5 rounded-full bg-primary shrink-0" />
              <span className="text-foreground">{field}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="flex justify-end">
        <Button size="lg" onClick={handleSave}>Save Configuration</Button>
      </div>
    </div>
  );
};

export default RegulatorAgreementTemplates;
